---
title: "Predicting Appliance Energy Use "
author: "Tony Bui"
date: "2018 August 18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
***
# Predicting Appliance Energy Use

### What?

This project will create a model to predict appliance energy use in a house.


### Who and Why?

The clients are electric utility companies. These companies need to be able to predict household energy demand accurately. If they produce too much electricity, energy will be wasted and costs will rise. On the other hand, if not enough electricity is produced, there will be power outages and customer satisfaction will fall.


### Data Source

The data is located on the [UCI Machine Learning Repository](http://archive.ics.uci.edu/ml/datasets/Appliances+energy+prediction). Observations were collected every 10 minutes for about 4.5 months.  

* M-bus energy meters logged the electricity usage in *Wh* watt-hours.
* ZigBee wireless sensors collected *T* temperature in degrees Celsius and *RH* relative humidity readings inside the house's rooms.
* Outside weather conditions from the nearest airport weather station (Chievres Airport, Belgium) came from the Reliable Prognosis public dataset.


### Approach

The initial approach will be to create a multiple linear regression model. The dependent variable will be appliance energy use. The explanatory variables will be some combination of the following:  

* date and time
* light fixture energy use
* indoor temperature and humidity
* outdoor weather conditions


### Deliverables

* R code that was used for analysis
* Slides presenting the results
